### ISSUE TITLE
"SQLite package has not been found installed" in docker image

### ISSUE THREAD

**Issue by msawatzky75** [msawatzky75/discord-bot-js#27]
```
/app/.yarn/__virtual__/typeorm-virtual-0c665e7039/0/cache/typeorm-npm-0.2.40-6de1623692-f8756c965c.zip/node_modules/typeorm/error/TypeORMError.js:9
        var _this = _super.call(this, message) || this;
                           ^

DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save
    at DriverPackageNotInstalledError.TypeORMError [as constructor] (/app/.yarn/__virtual__/typeorm-virtual-0c665e7039/0/cache/typeorm-npm-0.2.40-6de1623692-f8756c965c.zip/node_modules/typeorm/error/TypeORMError.js:9:28)
    at new DriverPackageNotInstalledError (/app/.yarn/__virtual__/typeorm-virtual-0c665e7039/0/cache/typeorm-npm-0.2.40-6de1623692-f8756c965c.zip/node_modules/typeorm/error/DriverPackageNotInstalledError.js:12:23)
    at SqliteDriver.loadDependencies (/app/.yarn/__virtual__/typeorm-virtual-0c665e7039/0/cache/typeorm-npm-0.2.40-6de1623692-f8756c965c.zip/node_modules/typeorm/driver/sqlite/SqliteDriver.js:129:19)
    at new SqliteDriver (/app/.yarn/__virtual__/typeorm-virtual-0c665e7039/0/cache/typeorm-npm-0.2.40-6de1623692-f8756c965c.zip/node_modules/typeorm/driver/sqlite/SqliteDriver.js:29:15)
    at DriverFactory.create (/app/.yarn/__virtual__/typeorm-virtual-0c665e7039/0/cache/typeorm-npm-0.2.40-6de1623692-f8756c965c.zip/node_modules/typeorm/driver/DriverFactory.js:45:24)
    at new Connection (/app/.yarn/__virtual__/typeorm-virtual-0c665e7039/0/cache/typeorm-npm-0.2.40-6de1623692-f8756c965c.zip/node_modules/typeorm/connection/Connection.js:53:59)
    at ConnectionManager.create (/app/.yarn/__virtual__/typeorm-virtual-0c665e7039/0/cache/typeorm-npm-0.2.40-6de1623692-f8756c965c.zip/node_modules/typeorm/connection/ConnectionManager.js:62:26)
    at /app/.yarn/__virtual__/typeorm-virtual-0c665e7039/0/cache/typeorm-npm-0.2.40-6de1623692-f8756c965c.zip/node_modules/typeorm/globals.js:70:66
    at step (/app/.yarn/cache/tslib-npm-2.3.1-0e21e18015-de17a98d46.zip/node_modules/tslib/tslib.js:143:27)
    at Object.next (/app/.yarn/cache/tslib-npm-2.3.1-0e21e18015-de17a98d46.zip/node_modules/tslib/tslib.js:124:57)
```

Maybe 
```
apt install sqlite3
```
could fix the issue?

**Comment by YodelingClam** [comment]
didnt you fix this

**Comment by msawatzky75** [comment]
typeorm and sqlite have been removed as depenencies, so this is no longer a concern
